/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/h0WGfaInu0G
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Rubik } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { signIn } from "next-auth/react"

export function Login() {

  return (
    <div className="flex flex-col h-full justify-center space-y-4">
      <div className="space-y-2 text-center">
        <h1 className="text-3xl font-bold">Login</h1>
        <p className="text-gray-500 dark:text-gray-400">Enter your email below to login to your account</p>
      </div>
      <div className="mx-auto w-[300px] space-y-4">
        <Button className="w-full" onClick={async () => { signIn('google') }}>Login with Google</Button>
        <Button className="w-full" onClick={async () => { signIn('discord') }}>Login with Discord</Button>
      </div>
    </div>
  )
}
