/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/EvRbnkxJ6g2
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from '@/components/ui/button'
import { RefreshCcw } from 'lucide-react'

export function Reload({onClick}:{onClick : () => void}) {    return (
        <div className="fixed bottom-[4.5rem] right-4 z-50">
                <Button onClick={onClick} className ="flex h-10 w-10 p-0 items-center justify-center rounded-full bg-gray-900 text-gray-50 shadow-md transition-colors hover:bg-gray-900/90 focus:outline-none focus:ring-2 focus:ring-gray-950 focus:ring-offset-2 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus:ring-gray-300">
                    <RefreshCcw/>
                </Button>
        </div>
    )
}
